export default function Head() {
  return (
    <>
      <title>SuperMetrics Heart Book</title>
      <meta name="description" content="Generated by create next app" />
      <meta content="initial-scale=1width=device-width" name="viewport" />
      <link rel="icon" href="/diversity1.ico" />
    </>
  )
}
