export default function DefaultTags() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <meta content="initial-scale=1width=device-width" name="viewport" />
      <link rel="icon" href="/diversity1.ico" />
    </>
  );
}
